### ISSUE TITLE
Avoid loading font on page load

### ISSUE THREAD

**Issue by AmitMY** [sutton-signwriting/sgnw-components#7]
Hi Steve,

Usually, web fonts load on demand.
However, when including `sgnw-components`, despite not using it, the fonts are immediately loaded.

This causes "first paint" performance issues, as the fonts weigh 10.5MB (a lot!), and are not necessarily needed for the first load.

It would be nice if the fonts won't load on init, that way, they will be lazy loaded.

---

For now, in order to only load the fonts after page load, I do:
```js
import {defineCustomElements} from '@sutton-signwriting/sgnw-components/loader';
window.addEventListener('load', () => defineCustomElements());
```
But this isn't great, for cases where I have sign writing elements on first load (my scenario sometimes has them, sometimes not)

**Comment by Slevinski** [comment]
Hi Amit,

I can see the issue.  The component package startup is the cause.

The global script runs once for the entire component set.  Ignore the color functions.
https://github.com/sutton-signwriting/sgnw-components/blob/master/src/global/global.ts

    import { cssAppend, cssLoaded } from '@sutton-signwriting/font-ttf/font/font.min.mjs';

    declare global {
      interface Window { sgnw: boolean; }
    }
    window['sgnw'] = false;
    
    const event = new Event('sgnw');

    export default function() { // or export default async function()
      cssAppend();
      cssLoaded( ()=> {
        window['sgnw'] = true;
        window.dispatchEvent(event);
      });
    }

Functions
* cssAppend - adds the font-face declaration
* cssLoaded - accepts a callback function when the font is loaded and ready to use

Variables:
* window['sgnw']
** if false, the components do nothing and wait.
** if true, the components know the fonts are ready.
* event - signal that fonts are ready

For people who have the SignWriting fonts installed, there is no startup cost.  The cssAppend will point to a local copy of the font and nothing needs to be downloaded.

For people who don't have the SignWriting fonts, the cssLoaded function uses the font on a canvas which initiates the font download.   Once ready, an event is triggered and the components turn on.

By design, the components turn on automatically.

For your scenario, I'm not sure what is the best way to make that happen.  Lazy loading of fonts cause the components to render incorrectly and components will not redraw when the fonts are ready.

If you are worried about first paint, I could delay the call to cssLoaded until after first paint.

**Comment by AmitMY** [comment]
Thanks, Steve!
really what I care for is to load the fonts on-demand - only when needed.
I can create some workaround on my end, but it would be nice if this was automatic.

Delaying to after "first-paint" (and always loading) is not the best strategy imo if the font is indeed required for the first paint, and also the page will still "load" even after the paint. 


I just want users of my app to be able to open it as quick as possible (on mobile), and then download whatever else needed in the background when necessary :) 

I'll post my workaround here once I address it!

**Comment by Slevinski** [comment]
I'm open to any redesign ideas.  I'll need to dig into Stencil docs and discussions.  I can think of three different startup options.  I have a few vague ideas.

One idea is to move the creation of the variable window['sgnw'] from the global script to the components.  If the variable doesn't exist, the first component will create it as undefined and sleep until the event when the font is ready.

The global script would periodically check for the existence of the variable window['sgnw'].  When the variable window['sgnw'] appears with a value of undefined, the watcher will set the variable to false, stop the periodic checks, and call a font loading function.

The font loading function would check the font.  While false, it will wait.  Once true, the function will set the variable window['sgnw'] to true and signal the event.

The font loading function could also be called directly to preload the fonts.

**Comment by Slevinski** [comment]
New version published using an updated @sutton-signwriting/font-ttf.  This should fix the issue.
